Repository soed2020-teamorange/ch.bfh.bti7081.s2020.orange, pull requests merged in 2020-05, with the labels that each got.

#57 Bugfix/persistence and assignments
  src/main/java/ch/bfh/bti7081/s2020/orange/Application.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/data/entities/MedicalSpecialist.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/data/entities/Patient.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/data/entities/User.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/repositories/PatientRepository.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/repositories/UserBaseRepository.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/service/MedicalSpecialistService.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/service/PatientService.java
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/views/editUserInfos/EditUserInfosViewImpl.java
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/views/showUserInfos/ShowUserPresenterImpl.java
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/views/showUserInfos/ShowUserView.java
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/views/showUserInfos/ShowUserViewImpl.java
Labels: bug, high priority, task

#60 Add emergency button at main view
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/MainView.java
Labels: enhancement, medium priority, task

#62 Initial version for adding activities
  package-lock.json
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/data/entities/Activity.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/data/entities/ActivityDiary.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/data/entities/ActivityEntry.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/data/entities/Patient.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/repositories/ActivityDiaryRepository.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/repositories/ActivityEntryRepository.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/repositories/DiaryBaseRepository.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/repositories/MoodDiaryRepository.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/service/ActivityEntryService.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/service/DiaryService.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/service/PatientActivityDiaryService.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/service/PatientMoodDiaryService.java
  src/main/java/ch/bfh/bti7081/s2020/orange/backend/service/PatientService.java
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/MainView.java
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/utils/AppConst.java
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/views/activity_diary/create_entry/ActivityDiaryCreateEntryPresenter.java
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/views/activity_diary/create_entry/ActivityDiaryCreateEntryPresenterImpl.java
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/views/activity_diary/create_entry/ActivityDiaryCreateEntryView.java
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/views/activity_diary/create_entry/ActivityDiaryCreateEntryViewImpl.java
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/views/activity_diary/create_entry/ActivityDiaryCreateEntryViewRoute.java
Labels: enhancement

#67 Add contextMenu overlay on top of emergency button, change links to p…
  frontend/styles/shared-styles.css
  package-lock.json
  src/main/java/ch/bfh/bti7081/s2020/orange/Application.java
  src/main/java/ch/bfh/bti7081/s2020/orange/ui/AppView.java
Labels: enhancement, low priority, task
